buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = "1.9.3"
group = "com.spl.auctionflipper"
archivesBaseName = "spl-auctionflipper"

minecraft {
    version = "1.8.9"
    runDir = "run"
}

dependencies {
    // Add any dependencies here
}